export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_MOBILEPRODUCTS = "FETCH_MOBILEPRODUCTS";

export const FILTER_BY_TITLE = "FILTER_BY_TITLE";
export const SORT_BY_PRICE = "SORT_BY_PRICE";

export const WISHLIST_ITEM = "WISHLIST_ITEM";
